name: dribbbledanimation
description: A new Flutter project.
version: 1.0.6+11

environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  font_awesome_flutter: '>= 4.7.0'
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.1
  firebase_database: ^3.1.6
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7 
  firebase_analytics:
  firebase_storage: 
  
    
  google_sign_in: ^4.4.4
  shared_preferences: ^0.5.6+3
  random_string: ^2.0.1
  loading: ^1.0.2
  http: ^0.12.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: "^0.15.2"
  flutter_bloc: ^6.0.5
  native_share: ^1.0.0
  image_picker: ^0.6.0+9
  social_share_plugin: ^0.3.1+1
  esys_flutter_share: ^1.0.2
  share: ^0.6.5+4
  storage_path: ^0.0.8
  transparent_image: ^1.0.0
  flutter_staggered_grid_view: "^0.3.2"
  receive_sharing_intent: ^1.4.0+2
  cached_network_image: ^2.0.0-rc
  provider:
  firebase_messaging: ^6.0.13
  url_launcher:
  google_fonts: ^0.3.9 
  firebase_remote_config: ^0.3.0+3
  package_info: ^0.4.1
  video_player: ^0.10.12+2
  flutter_link_preview: ^1.5.6
  pdf_flutter: ^1.1.3
  downloads_path_provider: ^0.1.0
  flutter_downloader: ^1.5.1
dev_dependencies:
   test:
   flutter_test: 
     sdk: flutter
   flutter_launcher_icons: "^0.7.3"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   
  - assets/login.jpg
  - assets/home.jpeg
  - assets/tick.png
  - assets/RC_APP.jpeg
  - assets/logo_rcpng.png
  - assets/google_logo.png
  - assets/avatars/avatar-1.jpg
  - assets/avatars/avatar-2.jpg
  - assets/avatars/avatar-3.jpg
  - assets/avatars/avatar-4.jpg
  - assets/avatars/avatar-5.jpg
  - assets/avatars/avatar-6.jpg
  - assets/avatars/default-avatar.jpg
  - assets/iconos/
  - assets/iconos/menuDerecho/
  - assets/images/icon-48.png
  - assets/images/icon-480.png
  - assets/images/icon-400.png
  - assets/images/qr.png
  - assets/images/bulb.png
  - assets/images/google_logo.png
  - assets/images/pdf.png
  
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Literata
      fonts:
        - asset: assets/fonts/Literata/Literata-VariableFont_wght.ttf
    - family: Colibri
      fonts:
        - asset: assets/fonts/colibri/Calibri Bold.TTF
        - asset: assets/fonts/colibri/Calibri Bold Italic.ttf
        - asset: assets/fonts/colibri/Calibri Italic.ttf
        - asset: assets/fonts/colibri/Calibri Light.ttf
        - asset: assets/fonts/colibri/Calibri Light Italic.ttf
        - asset: assets/fonts/colibri/Calibri Regular.ttf
    - family: TwitterIcon
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeue400.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue500.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeue600.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNeue700.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue800.ttf
          weight: 800
        - asset: assets/fonts/HelveticaNeue900.ttf
          weight: 900
        - asset: assets/fonts/HelveticaNeueIt.ttf
          style: italic
     
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
  